apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
replicas:
- name: vote
  count: 3
images:
- name: docker.io/schoolofdevops/vote
  newTag: v4
namespace: instavote
commonLabels:
  project: instavote
  env: dev
commonAnnotations:
  supported-by: yourmom
